# Generated by Django 5.2 on 2025-04-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('patient', 'question')},
        ),
    ]
