# Generated by Django 5.2 on 2025-04-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_alter_question_number_alter_response_unique_together'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='response',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='response',
            name='attempt',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('patient', 'question', 'attempt')},
        ),
    ]
