# Generated by Django 5.2 on 2025-04-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clinicianprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicianprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
