# Generated by Django 5.2 on 2025-04-25 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_testattempt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestAttempt',
        ),
    ]
