# Generated by Django 5.2 on 2025-04-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('specialization', models.CharField(choices=[('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Dermatology', 'Dermatology'), ('Orthopedics', 'Orthopedics'), ('Pediatrics', 'Pediatrics'), ('Dentistry', 'Dentistry'), ('Psychiatry', 'Psychiatry'), ('Gastroenterology', 'Gastroenterology'), ('Endocrinology', 'Endocrinology')], max_length=100)),
                ('experience_years', models.IntegerField()),
                ('clinic_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('available_for', models.CharField(choices=[('chat', 'Chat'), ('video', 'Video Call'), ('physical', 'Physical Visit')], max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
