# Generated by Django 5.2 on 2025-04-27 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('available', models.BooleanField(default=True)),
                ('location_city', models.CharField(max_length=100)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='AmbulanceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('pickup_address', models.TextField()),
                ('emergency_type', models.CharField(choices=[('normal', 'Normal'), ('critical', 'Critical')], max_length=50)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('ambulance_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambulance.ambulanceservice')),
            ],
        ),
    ]
